"""initial_schema_with_logistics_and_services

Revision ID: 5044685dba9b
Revises: 
Create Date: 2026-03-02 12:07:54.178959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5044685dba9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Categories and attributes system
    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('icon', sa.String(), nullable=True),
        sa.Column('color', sa.String(), nullable=True),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('legacy_product_type', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    
    op.create_table('category_attributes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('attribute_type', sa.String(), nullable=True),
        sa.Column('required', sa.Boolean(), nullable=True),
        sa.Column('sort_order', sa.Integer(), nullable=True),
        sa.Column('options', sa.JSON(), nullable=True),
        sa.Column('min_value', sa.Float(), nullable=True),
        sa.Column('max_value', sa.Float(), nullable=True),
        sa.Column('max_length', sa.Integer(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('product_metadata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=False),
        sa.Column('attribute_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['attribute_id'], ['category_attributes.id'], ),
        sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Users and locations
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('roles', sa.String(), nullable=False),
        sa.Column('city_id', sa.String(), nullable=True),
        sa.Column('approved', sa.Boolean(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('establishment_type', sa.String(), nullable=True),
        sa.Column('production_capacity', sa.Integer(), nullable=True),
        sa.Column('delivery_capacity', sa.Integer(), nullable=True),
        sa.Column('operating_hours', sa.String(), nullable=True),
        sa.Column('tipos_produtos', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_city_id'), 'users', ['city_id'], unique=False)
    
    op.create_table('delivery_locations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('address', sa.String(), nullable=False),
        sa.Column('city_id', sa.String(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('contact_person', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('capacity', sa.Integer(), nullable=True),
        sa.Column('daily_need', sa.Integer(), nullable=True),
        sa.Column('operating_hours', sa.String(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('approved', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_locations_city_id'), 'delivery_locations', ['city_id'], unique=False)
    
    # Product batches
    op.create_table('product_batches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('product_type', sa.Enum('MEAL', 'INGREDIENT', 'CLOTHING', 'MEDICINE', 'HYGIENE', 'CLEANING', 'SCHOOL_SUPPLIES', 'BABY_ITEMS', 'PET_SUPPLIES', 'GENERIC', name='producttype'), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('quantity_available', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('metadata_cache', sa.JSON(), nullable=True),
        sa.Column('status', sa.Enum('PRODUCING', 'READY', 'IN_DELIVERY', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='batchstatus'), nullable=True),
        sa.Column('donated_ingredients', sa.Boolean(), nullable=True),
        sa.Column('pickup_deadline', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('ready_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Deliveries with logistics and services support
    op.create_table('deliveries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('batch_id', sa.Integer(), nullable=True),
        sa.Column('pickup_location_id', sa.Integer(), nullable=True),
        sa.Column('delivery_location_id', sa.Integer(), nullable=False),
        sa.Column('volunteer_id', sa.Integer(), nullable=True),
        sa.Column('parent_delivery_id', sa.Integer(), nullable=True),
        sa.Column('product_type', sa.Enum('MEAL', 'INGREDIENT', 'CLOTHING', 'MEDICINE', 'HYGIENE', 'CLEANING', 'SCHOOL_SUPPLIES', 'BABY_ITEMS', 'PET_SUPPLIES', 'GENERIC', name='producttype'), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('AVAILABLE', 'PENDING_CONFIRMATION', 'RESERVED', 'PICKED_UP', 'IN_TRANSIT', 'IN_PROGRESS', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='deliverystatus'), nullable=True),
        sa.Column('metadata_cache', sa.JSON(), nullable=True),
        sa.Column('pickup_code', sa.String(), nullable=True),
        sa.Column('delivery_code', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.Column('picked_up_at', sa.DateTime(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('service_started_at', sa.DateTime(), nullable=True),
        sa.Column('service_completed_at', sa.DateTime(), nullable=True),
        sa.Column('requires_skills', sa.JSON(), nullable=True),
        sa.Column('estimated_time', sa.DateTime(), nullable=True),
        sa.Column('photo_proof', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['batch_id'], ['product_batches.id'], ),
        sa.ForeignKeyConstraint(['delivery_location_id'], ['delivery_locations.id'], ),
        sa.ForeignKeyConstraint(['parent_delivery_id'], ['deliveries.id'], ),
        sa.ForeignKeyConstraint(['pickup_location_id'], ['delivery_locations.id'], ),
        sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_delivery_pickup_location', 'deliveries', ['pickup_location_id'], unique=False)
    
    # Resource requests and reservations
    op.create_table('resource_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.Integer(), nullable=False),
        sa.Column('quantity_meals', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('IDLE', 'REQUESTING', 'OFFERING', 'PARTIALLY_RESERVED', 'RESERVED', 'IN_PROGRESS', 'AWAITING_PICKUP', 'PICKED_UP', 'IN_TRANSIT', 'PENDING_CONFIRMATION', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='orderstatus'), nullable=True),
        sa.Column('receiving_time', sa.DateTime(), nullable=True),
        sa.Column('confirmation_code', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('resource_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('request_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.Column('unit', sa.String(), nullable=False),
        sa.Column('quantity_reserved', sa.Float(), nullable=True),
        sa.Column('quantity_delivered', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['request_id'], ['resource_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('resource_reservations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('request_id', sa.Integer(), nullable=False),
        sa.Column('volunteer_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('IDLE', 'REQUESTING', 'OFFERING', 'PARTIALLY_RESERVED', 'RESERVED', 'IN_PROGRESS', 'AWAITING_PICKUP', 'PICKED_UP', 'IN_TRANSIT', 'PENDING_CONFIRMATION', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='orderstatus'), nullable=True),
        sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
        sa.Column('receipt_photo', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['request_id'], ['resource_requests.id'], ),
        sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('reservation_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reservation_id', sa.Integer(), nullable=False),
        sa.Column('resource_item_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['reservation_id'], ['resource_reservations.id'], ),
        sa.ForeignKeyConstraint(['resource_item_id'], ['resource_items.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Generic order model
    op.create_table('orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_type', sa.Enum('DONATION', 'REQUEST', 'PURCHASE', 'LOAN', name='ordertype'), nullable=False),
        sa.Column('product_type', sa.Enum('MEAL', 'INGREDIENT', 'CLOTHING', 'MEDICINE', 'HYGIENE', 'CLEANING', 'SCHOOL_SUPPLIES', 'BABY_ITEMS', 'PET_SUPPLIES', 'GENERIC', name='producttype'), nullable=False),
        sa.Column('status', sa.Enum('IDLE', 'REQUESTING', 'OFFERING', 'PARTIALLY_RESERVED', 'RESERVED', 'IN_PROGRESS', 'AWAITING_PICKUP', 'PICKED_UP', 'IN_TRANSIT', 'PENDING_CONFIRMATION', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='orderstatus'), nullable=True),
        sa.Column('requester_id', sa.Integer(), nullable=True),
        sa.Column('provider_id', sa.Integer(), nullable=True),
        sa.Column('beneficiary_id', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.Column('confirmation_codes', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('reserved_at', sa.DateTime(), nullable=True),
        sa.Column('in_progress_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['beneficiary_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Inventory system
    op.create_table('inventory_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shelter_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
        sa.Column('quantity_reserved', sa.Integer(), nullable=False),
        sa.Column('quantity_available', sa.Integer(), nullable=False),
        sa.Column('metadata_cache', sa.JSON(), nullable=True),
        sa.Column('min_threshold', sa.Integer(), nullable=True),
        sa.Column('max_threshold', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_transaction_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['shelter_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_shelter_id'), 'inventory_items', ['shelter_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_category_id'), 'inventory_items', ['category_id'], unique=False)
    
    op.create_table('inventory_transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('inventory_item_id', sa.Integer(), nullable=False),
        sa.Column('transaction_type', sa.Enum('DONATION_RECEIVED', 'DONATION_GIVEN', 'MANUAL_ADJUSTMENT', 'REQUEST_CREATED', 'REQUEST_CANCELLED', 'REQUEST_ADJUSTED', 'INITIAL_STOCK', 'EXPIRED', 'DAMAGED', name='transactiontype'), nullable=False),
        sa.Column('quantity_change', sa.Integer(), nullable=False),
        sa.Column('balance_after', sa.Integer(), nullable=False),
        sa.Column('reserved_after', sa.Integer(), nullable=False),
        sa.Column('available_after', sa.Integer(), nullable=False),
        sa.Column('delivery_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('transaction_metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
        sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_created_at'), 'inventory_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_inventory_item_id'), 'inventory_transactions', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    
    op.create_table('shelter_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shelter_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('quantity_requested', sa.Integer(), nullable=False),
        sa.Column('quantity_received', sa.Integer(), nullable=True),
        sa.Column('quantity_pending', sa.Integer(), nullable=True),
        sa.Column('quantity_cancelled', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('metadata_cache', sa.JSON(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('cancelled_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['shelter_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelter_requests_shelter_id'), 'shelter_requests', ['shelter_id'], unique=False)
    op.create_index(op.f('ix_shelter_requests_status'), 'shelter_requests', ['status'], unique=False)
    
    op.create_table('request_adjustments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('request_id', sa.Integer(), nullable=False),
        sa.Column('adjustment_type', sa.String(), nullable=False),
        sa.Column('quantity_before', sa.Integer(), nullable=False),
        sa.Column('quantity_after', sa.Integer(), nullable=False),
        sa.Column('quantity_change', sa.Integer(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('can_adjust', sa.Boolean(), nullable=True),
        sa.Column('warning_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['request_id'], ['shelter_requests.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_adjustments_request_id'), 'request_adjustments', ['request_id'], unique=False)
    
    op.create_table('shelter_request_deliveries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('request_id', sa.Integer(), nullable=False),
        sa.Column('delivery_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ),
        sa.ForeignKeyConstraint(['request_id'], ['shelter_requests.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('distribution_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shelter_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('recipient_name', sa.String(), nullable=True),
        sa.Column('recipient_document', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('distribution_metadata', sa.JSON(), nullable=True),
        sa.Column('photo_proof', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('cancelled_at', sa.DateTime(), nullable=True),
        sa.Column('cancellation_reason', sa.Text(), nullable=True),
        sa.Column('distributed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['shelter_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_records_distributed_at'), 'distribution_records', ['distributed_at'], unique=False)
    op.create_index(op.f('ix_distribution_records_shelter_id'), 'distribution_records', ['shelter_id'], unique=False)
    op.create_index(op.f('ix_distribution_records_status'), 'distribution_records', ['status'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distribution_records_status'), table_name='distribution_records')
    op.drop_index(op.f('ix_distribution_records_shelter_id'), table_name='distribution_records')
    op.drop_index(op.f('ix_distribution_records_distributed_at'), table_name='distribution_records')
    op.drop_table('distribution_records')
    op.drop_table('shelter_request_deliveries')
    op.drop_index(op.f('ix_request_adjustments_request_id'), table_name='request_adjustments')
    op.drop_table('request_adjustments')
    op.drop_index(op.f('ix_shelter_requests_status'), table_name='shelter_requests')
    op.drop_index(op.f('ix_shelter_requests_shelter_id'), table_name='shelter_requests')
    op.drop_table('shelter_requests')
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_inventory_item_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_created_at'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_items_category_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_shelter_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('orders')
    op.drop_table('reservation_items')
    op.drop_table('resource_reservations')
    op.drop_table('resource_items')
    op.drop_table('resource_requests')
    op.drop_index('idx_delivery_pickup_location', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('product_batches')
    op.drop_index(op.f('ix_delivery_locations_city_id'), table_name='delivery_locations')
    op.drop_table('delivery_locations')
    op.drop_index(op.f('ix_users_city_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('product_metadata')
    op.drop_table('category_attributes')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
